baseURL: https://devopsfromscratch.com
languageCode: en-us
title: DevOps From Scratch
theme: PaperMod

params:
    homeInfoParams:
        Title: Learn DevOps From Scratch
        Content: If you are an a beginner to DevOps and confused about everything, let me help you, for free!. Checkout [HERE](https://esc.sh/projects/devops-from-scratch/index.html)

