baseURL: /
languageCode: en-us
title: DevOpsWork
theme: PaperMod

params:
    homeInfoParams:
        Title: Welcome to DevOpsWork
        Content: Not much to see here for now. Checkout [HERE](https://esc.sh/projects/devops-from-scratch/index.html) for now

